import type { AppProps } from '@/types/external/Application'

export const apps: Array<AppProps> = [
  {
    'App Ref': '0',
    'App Key': 'XXX',
    'Application Name': '8.0/Airport/Lounge',
    'PII Data': 'FALSE',
    'Tier Level': '1 - Critical',
    PCI: 'FALSE',
    'EQA Test Cases': 'FALSE',
    SME: 'Sim, Roger',
    'Queue Manager(s)': '[]',
    Nodes: '[]',
    Notes: 'Mobile team has EQA test cases to validate',
    'Application Image':
      'https://img.freepik.com/free-photo/airport-terminal_1417-1461.jpg?w=1380&t=st=1706207145~exp=1706207745~hmac=58b6066fc95d14fd7911ee9432058518d280ccb94b53cec9d746baa72abb9302 https://lucid.app/documents/embedded/af6499bc-4f73-4fad-9760-51a192ec46e8',
    'Who are my dependencies?':
      'SQL Database, VMs, ODM, KAFKA (on-prem), MQ, F5',
  },
  {
    'App Ref': '1',
    'App Key': 'BCR',
    'Application Name': 'Airframe',
    'PII Data': 'TRUE',
    'Tier Level': '1 - Critical',
    PCI: 'TRUE',
    'EQA Test Cases': 'FALSE',
    SME: 'Wareham, Shane',
    'Queue Manager(s)': '[]',
    Nodes: '[]',
    'Application Image':
      'https://lucid.app/documents/embedded/cede49ab-f91b-4f50-8a82-76549da39883 https://img.freepik.com/free-photo/airport-terminal_1417-1461.jpg?w=1380&t=st=1706207145~exp=1706207745~hmac=58b6066fc95d14fd7911ee9432058518d280ccb94b53cec9d746baa72abb9302 https://img.freepik.com/free-photo/woman-walks-along-airport-with-suitcases_93675-131318.jpg?w=1380&t=st=1706207302~exp=1706207902~hmac=33e3baccf8641cbe967f436aaef51f3fe051248f5e63bf9f868f0e7e480980db',
    'Who are my dependencies?': 'NONE',
  },
  {
    'App Ref': '2',

    'App Key': 'NAE',
    'Application Name': 'Builds',
    'PII Data': 'TRUE',
    'Tier Level': '2 - Somewhat Critical',
    PCI: 'FALSE',
    'EQA Test Cases': 'TRUE',
    SME: 'Wareham, Shane;Chakrabarty, Shubhajeet',
    'Queue Manager(s)': '[]',
    Nodes: '[]',
    Notes:
      'this app has ACE but no MQ - and is used with Team City to build our bar files',
    'Application Image':
      'https://lucid.app/documents/embedded/cede49ab-f91b-4f50-8a82-76549da39883',
    'Who are my dependencies?': 'all apps need to have builds',
  },
  {
    'App Ref': '3',

    'App Key': 'CVF',
    'Application Name': 'LEID Management (cloud)',
    'PII Data': 'FALSE',
    'Tier Level': '1 - Critical',
    PCI: 'FALSE',
    'EQA Test Cases': 'FALSE',
    SME: 'Sim, Roger;Wareham, Shane',
    'Queue Manager(s)': '[]',
    Nodes: '[]',
    Notes: 'Active-Active on East-1 and East-2, load balanced with Route 53.',
    'Application Image':
      'https://lucid.app/documents/embedded/9a41d6af-c3dd-4806-9f7b-1f9dac9c5c83',
    'Who are my dependencies?': 'AWS Elasticache Redis',
  },
  {
    'App Ref': '4',
    'App Key': 'BPH',
    'Application Name': 'LEID Management (on-prem)',
    'PII Data': 'FALSE',
    'Tier Level': '1 - Critical',
    PCI: 'FALSE',
    'EQA Test Cases': 'TRUE',
    SME: 'Wareham, Shane;Sim, Roger',
    'Queue Manager(s)': '[]',
    Nodes: '[]',
    'Application Image':
      'https://lucid.app/documents/embedded/af6499bc-4f73-4fad-9760-51a192ec46e8',
    'Who are my dependencies?': 'CouchBase, VMs, DataPower, FluentD, F5',
  },
  {
    'App Ref': '5',

    'App Key': 'DWF',
    'Application Name': 'MongoMessenger',
    'PII Data': 'FALSE',
    'Tier Level': '4 - Not Critical',
    PCI: 'FALSE',
    'EQA Test Cases': 'TRUE',
    SME: 'Sim, Roger',
    'Queue Manager(s)': '[]',
    Nodes: '[]',
    Notes:
      'MongoMessenger service is a .Net Core REST microservice that will run on-prem for the first phase of STM deployment. Subsequent phases will involve the service being containerized and running in the cloud.',
    'Application Image':
      'https://lucid.app/documents/embedded/cede49ab-f91b-4f50-8a82-76549da39883',
    'Who are my dependencies?':
      'SHARES TPF environment via MongoDB data store.',
  },
  {
    'App Ref': '6',

    'App Key': 'CDE',
    'Application Name': 'PI ACE Services',
    'PII Data': 'FALSE',
    'Tier Level': '1 - Critical',
    PCI: 'FALSE',
    'EQA Test Cases': 'FALSE',
    SME: 'Fink, Mike',
    'App Number': 4,
    'Queue Manager(s)': '[]',
    Nodes:
      'TAWGAN01,TAWGAN02,SAWGAN01,SAWGAN02,SBFFAN01,QBFFAN01,QBFFAN02,PAWGAN01,PAWGAN02,PBFFAN01,PBFFAN02',
    'Application Image':
      'https://lucid.app/documents/embedded/cede49ab-f91b-4f50-8a82-76549da39883',
    'Who are my dependencies?': 'Virtual Machine must be running\r\n',
  },
  {
    'App Ref': '7',

    'App Key': 'AZJ',
    'Application Name': 'PI ACI History',
    'PII Data': 'TRUE',
    'Tier Level': '2 - Somewhat Critical',
    PCI: 'FALSE',
    'EQA Test Cases': 'FALSE',
    SME: 'Balasubramanian, Gayathri',
    'App Number': 1,
    'Queue Manager(s)': 'PIACMQ01,PIACMQ02,QIACMQ01,QIACMQ02,TIACMQ01,TIACMQ02',
    Nodes: 'PAWGAN01,PAWGAN02,SAWGAN01,SAWGAN02,DAWGAN01,QAWGAN01,QAWGAN02',
    Notes:
      'ACI = Advanced Check In: When a flight takes off. We receive messages about flight history and put it in the database - baggage info, details, %23 of passengers on the flight, etc.\r\n\r\nShares gives us flight history. PI reaches out to SHARES and enters it in database, then EDW Team pulls from that database.',
    'Application Image':
      'https://lucid.app/documents/embedded/cede49ab-f91b-4f50-8a82-76549da39883',
    'Who are my dependencies?':
      'SHARES, MQ, FLIFO, Oracle Database, Pseudo City Table',
  },
  {
    'App Ref': '8',

    'App Key': 'EJJ',
    'Application Name': 'PI AI',
    'PII Data': 'TRUE',
    'Tier Level': '2 - Somewhat Critical',
    PCI: 'FALSE',
    'EQA Test Cases': 'FALSE',
    SME: 'Fink, Mike',
    'Queue Manager(s)': '[]',
    Nodes: '[]',
    'Application Image':
      'https://lucid.app/documents/embedded/9a41d6af-c3dd-4806-9f7b-1f9dac9c5c83',
    'Who are my dependencies?': 'NONE',
  },
  {
    'App Ref': '9',

    'App Key': 'EFD',
    'Application Name': 'PI APIS Query',
    'PII Data': 'TRUE',
    'Tier Level': '3 - Less Critical',
    PCI: 'FALSE',
    'EQA Test Cases': 'TRUE',
    SME: 'Thalari, Nagendra Kumar',
    'Queue Manager(s)': '[]',
    Nodes: '[]',
    'Application Image':
      'https://lucid.app/documents/embedded/9a41d6af-c3dd-4806-9f7b-1f9dac9c5c83',
    'Who are my dependencies?': 'NONE',
  },
  {
    'App Ref': '10',

    'App Key': 'CXK',
    'Application Name': 'PI Availability Manager',
    'PII Data': 'FALSE',
    'Tier Level': '2 - Somewhat Critical',
    PCI: 'FALSE',
    'EQA Test Cases': 'TRUE',
    SME: 'Hieber, Kymberly',
    'App Number': 29,
    'Queue Manager(s)': 'QIACMQ01,QIACMQ02,PIACMQ01,PIACMQ02,TIACMQ01,TIACMQ02',
    Nodes: 'TCXKAN02,TCXKAN01,SCXKAN01,SCXKAN02,QCXKAN01,QCXKAN02',
    'Application Image':
      'https://lucid.app/documents/embedded/9a41d6af-c3dd-4806-9f7b-1f9dac9c5c83 https://lucid.app/documents/embedded/9a41d6af-c3dd-4806-9f7b-1f9dac9c5c83',
    'Who are my dependencies?': 'AWS Kibana(Data Lake)',
  },
  {
    'App Ref': '11',

    'App Key': 'HAS',
    'Application Name': 'PI AWS Services',
    'PII Data': 'TRUE',
    'Tier Level': '2 - Somewhat Critical',
    PCI: 'FALSE',
    'EQA Test Cases': 'TRUE',
    SME: 'Hieber, Kymberly',
    'App Number': 28,
    'Queue Manager(s)': '[]',
    Nodes: '[]',
    Notes: 'PI AWS Services = Data Lake',
    'Application Image':
      'https://lucid.app/documents/embedded/9a41d6af-c3dd-4806-9f7b-1f9dac9c5c83',
    'Who are my dependencies?': 'ECS, OAM',
  },
  {
    'App Ref': '12',

    'App Key': 'APB',
    'Application Name': 'PI Capture Store',
    'PII Data': 'TRUE',
    'Tier Level': '2 - Somewhat Critical',
    PCI: 'FALSE',
    'EQA Test Cases': 'TRUE',
    SME: 'Hieber, Kymberly',
    'App Number': 16,
    'Queue Manager(s)': 'QIACMQ01,QIACMQ02,PIACMQ01,PIACMQ02,TIACMQ01,TIACMQ02',
    Nodes: 'PAPBAN01,PAPBAN02,SAPBAN01,SAPBAN02,DAPBAN01,QAPBAN01,QAPBAN02',
    'Application Image':
      'https://lucid.app/documents/embedded/9a41d6af-c3dd-4806-9f7b-1f9dac9c5c83',
    'Who are my dependencies?': 'NONE',
  },
  {
    'App Ref': '13',

    'App Key': 'BVC',
    'Application Name': 'PI Credit Auth',
    'PII Data': 'TRUE',
    'Tier Level': '1 - Critical',
    PCI: 'TRUE',
    'EQA Test Cases': 'TRUE',
    SME: 'Anaganti, Naveen',
    'App Number': 17,
    'Queue Manager(s)': 'PIACMQ01,PIACMQ02,QIACMQ01,QIACMQ02,TIACMQ01,TIACMQ02',
    Nodes: 'PAWGAN01,PAWGAN02,SAWGAN01,SAWGAN02,DAWGAN01,QAWGAN01,QAWGAN02',
    Notes:
      'Token is a payment service on the CSL Platform\r\nPayment Broker is the back-end piece that processes the credit card. It passes the token to merchandising.',
    'Application Image':
      'https://lucid.app/documents/embedded/cede49ab-f91b-4f50-8a82-76549da39883',
    'Who are my dependencies?': 'Token, Payment Broker\r\n',
  },
  {
    'App Ref': '14',

    'App Key': 'AHA',
    'Application Name': 'PI Dynamic Flight Selection',
    'PII Data': 'FALSE',
    'Tier Level': '1 - Critical',
    PCI: 'FALSE',
    'EQA Test Cases': 'TRUE',
    SME: 'Balasubramanian, Gayathri',
    'App Number': 2,
    'Queue Manager(s)': 'QIACMQ01,QIACMQ02,PIACMQ02,PIACMQ01,TIACMQ01,TIACMQ02',
    Nodes:
      'PAHAAN01,PAHAAN02,SAHAAN01,SAHAAN02,QAHAAN01,QAHAAN02,TAHAAN01,TAAIAN02',
    Notes:
      'DFS = Dynamic Flight Selection. This is Contact Centers. This tells us what flights are available across the United network and on which dates\r\n\r\nDFS Returns Three Different Responses:\r\n1) 1st Availability: Shares>DFS>Schd Eng> Request is sent\r\n2) Availability: Shares>DFS>Schd Eng> Request is sent\r\n3) Schedule Display: Schd Eng>DFS>Shares\r\n\r\nSche Eng pertains to Information about flight schedules and availability (i.e. origin, destination, etc.)',
    'Application Image':
      'https://lucid.app/documents/embedded/cede49ab-f91b-4f50-8a82-76549da39883',
    'Who are my dependencies?': 'Schedule Engine, MQ, ETL MQ\r\n',
  },
  {
    'App Ref': '15',

    'App Key': 'CYK',
    'Application Name': 'PI EMD',
    'PII Data': 'TRUE',
    'Tier Level': '2 - Somewhat Critical',
    PCI: 'TRUE',
    'EQA Test Cases': 'TRUE',
    SME: 'Guddati, Anusha',
    'App Number': 30,
    'Queue Manager(s)': 'PIACMQ01,PIACMQ02,QIACMQ01,QIACMQ02,TIACMQ01,TIACMQ02',
    Nodes:
      'PCYKAN02,PCYKAN01,QCYKAN01,QCYKAN02,TCYKAN01,SCYKAN01,SCYKAN02,DCYKAN01',
    'Application Image':
      'https://lucid.app/documents/embedded/2fee6c99-a2d3-4f57-b400-fbdfbe84a357',
    'Who are my dependencies?': 'SHARES  & EMD',
  },
  {
    'App Ref': '16',

    'App Key': 'CUO',
    'Application Name': 'PI Employee Number Service',
    'PII Data': 'TRUE',
    'Tier Level': '3 - Less Critical',
    PCI: 'FALSE',
    'EQA Test Cases': 'FALSE',
    SME: 'Anaganti, Naveen',
    'App Number': 27,
    'Queue Manager(s)': 'DAHAMQ01,DAHAMQ02,PAHAMQ01,PAHAMQ02,SAHAMQ01,SAHAMQ02',
    Nodes: '[]',
    'Application Image':
      'https://lucid.app/documents/embedded/9a41d6af-c3dd-4806-9f7b-1f9dac9c5c83',
    'Who are my dependencies?': 'Backend Employee JA Service\r\n',
  },
  {
    'App Ref': '17',
    'App Key': 'BHF',
    'Application Name': 'PI FQTV Services',
    'PII Data': 'TRUE',
    'Tier Level': '3 - Less Critical',
    PCI: 'FALSE',
    'EQA Test Cases': 'TRUE',
    SME: 'Chakrabarty, Shubhajeet',
    'App Number': 20,
    'Queue Manager(s)': 'PIACMQ02,PIACMQ01,QIACMQ01,QIACMQ02,TIACMQ01,TIACMQ02',
    Nodes: 'PBHFAN02,PBHFAN01,SBHFAN02,SBHFAN01,QBHFAN01,QBHFAN02',
    'Application Image':
      'https://lucid.app/documents/embedded/cede49ab-f91b-4f50-8a82-76549da39883',
    'Who are my dependencies?':
      'F5 , VA API ,Star API, UCB API , ODM( Future ), KAFKA( On Prem ) , AWS KAFKA( Future ), MQ, SQL Database',
  },
  {
    'App Ref': '18',
    'App Key': 'BHF',
    'Application Name': 'PI FQTV Services',
    'PII Data': 'TRUE',
    'Tier Level': '4 - Not Critical',
    PCI: 'FALSE',
    'EQA Test Cases': 'TRUE',
    SME: 'Sundaresan, Chandru;Chakrabarty, Shubhajeet;Reddy, Srinivas;Ghosh, Preetha;Xu, John',
    'Queue Manager(s)': '[]',
    Nodes: '[]',
    'Application Image':
      'https://lucid.app/documents/embedded/9a41d6af-c3dd-4806-9f7b-1f9dac9c5c83',
    'Who are my dependencies?': 'NONE',
  },
  {
    'App Ref': '19',
    'App Key': 'CPM',
    'Application Name': 'PI Google Fares',
    'PII Data': 'FALSE',
    'Tier Level': '1 - Critical',
    PCI: 'FALSE',
    'EQA Test Cases': 'FALSE',
    SME: 'Fink, Mike',
    'App Number': 22,
    'Queue Manager(s)': 'PIACMQ01,QIACMQ01,PIACMQ02,QIACMQ02,TIACMQ01,TIACMQ02',
    Nodes:
      'PCPMAN01,PCPMAN02,SCPMAN01,SCPMAN02,TCPMAN01,TCPMAN02,QCPMAN01,QCPMAN02,DCPMAN01',
    Notes:
      'We send a request to Datapower, which sends a message to FlightShopping',
    'Application Image':
      'https://lucid.app/documents/embedded/cede49ab-f91b-4f50-8a82-76549da39883',
    'Who are my dependencies?': 'Flight Shopping, SQL Database\r\n',
  },
  {
    'App Ref': '20',
    'App Key': 'APB',
    'Application Name': 'PI Green Screen',
    'PII Data': 'TRUE',
    'Tier Level': '3 - Less Critical',
    PCI: 'FALSE',
    'EQA Test Cases': 'TRUE',
    SME: 'Vullengala, Shravan',
    'Queue Manager(s)': 'PIACMQ01,PIACMQ02,QIACMQ01,QIACMQ02,TIACMQ01,TIACMQ02',
    Nodes: 'DAPBAN01,SAPBAN01,SAPBAN02,PAPBAN01,PAPBAN02,QAPBAN01,QAPBAN02',
    Notes:
      'TCP server & Port details:\r\nDEV - vcld16rdbkzap01.ual.com:7250\r\nQA - vcld36rqapbap01.ual.com:7250\r\nPROD - vcld34rpapbap01.ual.com:7250',
    'Application Image':
      'https://lucid.app/documents/embedded/cede49ab-f91b-4f50-8a82-76549da39883',
    'Who are my dependencies?': 'NONE',
  },
  {
    'App Ref': '21',
    'App Key': 'CCN',
    'Application Name': 'PI Interline Services',
    'PII Data': 'TRUE',
    'Tier Level': '2 - Somewhat Critical',
    PCI: 'FALSE',
    'EQA Test Cases': 'TRUE',
    SME: 'Shubhajeet, Chakrabarty',
    'App Number': 5,
    'Queue Manager(s)':
      'PIACMQ01,PIACMQ02,QIACMQ01,QIACMQ02,TIACMQ01,TIACMQ02,DAHAMQ02',
    Nodes:
      'PCCNAN01,PCCNAN02,SCCNAN01,SCCNAN02,QCCNAN02,QCCNAN01,TCCNAN01,TCCNAN02',
    Notes: 'planning to add PCI data with Paid Seats project in 2022',
    'Application Image':
      'https://lucid.app/documents/embedded/cede49ab-f91b-4f50-8a82-76549da39883',
    'Who are my dependencies?':
      'SHARES\r\nAirline File\r\nPI ODM\r\nStarDSP\r\nF5 , VM , ScheduleEngine  , CSLService , STAR Api , KAFKA(OnPrem ) , AWS KAFKA( Future ),  MQ , DataPower , SQL Database( Future )',
  },
  {
    'App Ref': '22',
    'App Key': 'BFF',
    'Application Name': 'PI Logging',
    'PII Data': 'TRUE',
    'Tier Level': '3 - Less Critical',
    PCI: 'FALSE',
    'EQA Test Cases': 'TRUE',
    SME: 'Balasubramanian, Gayathri',
    'App Number': 6,
    'Queue Manager(s)': 'PIACMQ01,PIACMQ02,QIACMQ01,QIACMQ02,TIACMQ01,TIACMQ02',
    Nodes:
      'PAWGAN01,PAWGAN02,SAWGAN01,SAWGAN02,DAWGAN01,QAWGAN01,QAWGAN02,TAWGAN02,TAWGAN01',
    Notes:
      'PI Logging:  Internal application where we log all requests/responses of applications into the database\r\nAll PI Applications use PI Logging',
    'Application Image':
      'https://lucid.app/documents/embedded/9a41d6af-c3dd-4806-9f7b-1f9dac9c5c83',
    'Who are my dependencies?': 'Database, MQ\r\n',
  },
  {
    'App Ref': '23',
    'App Key': 'AIM',
    'Application Name': 'PI MQ Gateway',
    'PII Data': 'TRUE',
    'Tier Level': '1 - Critical',
    PCI: 'TRUE',
    'EQA Test Cases': 'TRUE',
    SME: 'Balasubramanian, Gayathri',
    'App Number': 7,
    'Queue Manager(s)': '[]',
    Nodes: '[]',
    Notes:
      'MQ = Messaging Que Details\r\nReceives messages, processes them, sends back a response. The processing is done by our applications',
    'Application Image':
      'https://lucid.app/documents/embedded/9a41d6af-c3dd-4806-9f7b-1f9dac9c5c83',
    'Who are my dependencies?': 'None',
  },
  {
    'App Ref': '24',
    'App Key': 'BPD',
    'Application Name': 'PI ODM Business Rules',
    'PII Data': 'TRUE',
    'Tier Level': '3 - Less Critical',
    PCI: 'FALSE',
    'EQA Test Cases': 'TRUE',
    SME: 'Fink, Mike',
    'App Number': 8,
    'Queue Manager(s)': '[]',
    Nodes: '[]',
    Notes:
      "Currently on-prem, but planned to push it to the cloud.\r\nPart of ODM Business Rules is the decisions center.\r\nThe decision center is what builds it, then it's pushed to execution engine which will run in the cloud.\r\n",
    'Application Image':
      'https://lucid.app/documents/embedded/cede49ab-f91b-4f50-8a82-76549da39883',
    'Who are my dependencies?': 'VM, F5, SQL Database\r\n',
  },
  {
    'App Ref': '25',
    'App Key': 'AXR',
    'Application Name': 'PI PNR Claim',
    'PII Data': 'TRUE',
    'Tier Level': '3 - Less Critical',
    PCI: 'FALSE',
    'EQA Test Cases': 'TRUE',
    SME: 'Fink, Mike',
    'App Number': 9,
    'Queue Manager(s)': 'PIACMQ01,PIACMQ02,QIACMQ01,QIACMQ02,TIACMQ01,TIACMQ02',
    Nodes: 'PAWGAN01,PAWGAN02,SAWGAN01,SAWGAN02,DAWGAN01,QAWGAN01,QAWGAN02',
    Notes:
      "SHARES calls PI, we process it.\r\n\r\nTwo responses\r\n1) OUTBOUND: from PI through Tesa, going into SHARES, which goes to MQ\r\n2) INBOUND: SHARES>MQ>PNR Claim\r\n\r\nKIBANA is the tool that lets you see what's in the Data Lake",
    'Application Image':
      'https://lucid.app/documents/embedded/9a41d6af-c3dd-4806-9f7b-1f9dac9c5c83',
    'Who are my dependencies?': 'SHARES, Schedule Engine, Tesa, MQ\r\n',
  },
  {
    'App Ref': '26',
    'App Key': 'COA',
    'Application Name': 'PI PNR Retrieve',
    'PII Data': 'TRUE',
    'Tier Level': '4 - Not Critical',
    PCI: 'FALSE',
    'EQA Test Cases': 'TRUE',
    SME: 'Balasubramanian, Gayathri',
    'App Number': 10,
    'Queue Manager(s)': 'PIACMQ01,PIACMQ02,QIACMQ01,QIACMQ02,TIACMQ01,TIACMQ02',
    Nodes: 'PAWGAN01,PAWGAN02,SAWGAN01,SAWGAN02,DAWGAN01,QAWGAN01,QAWGAN02',
    Notes:
      'PNR = Passenger Name Record\r\nJust retrieves history of PNR. We get the history of PNR from Shares.',
    'Application Image':
      'https://lucid.app/documents/embedded/cede49ab-f91b-4f50-8a82-76549da39883',
    'Who are my dependencies?': 'Shares, MQ\r\n',
  },
  {
    'App Ref': '27',
    'App Key': 'AWG',
    'Application Name': 'PI PNR Update',
    'PII Data': 'TRUE',
    'Tier Level': '3 - Less Critical',
    PCI: 'FALSE',
    'EQA Test Cases': 'TRUE',
    SME: 'Balasubramanian, Gayathri',
    'App Number': 11,
    'Queue Manager(s)': 'PIACMQ01,PIACMQ02,QIACMQ01,QIACMQ02,TIACMQ01,TIACMQ02',
    Nodes: 'PAWGAN01,PAWGAN02,SAWGAN01,SAWGAN02,DAWGAN01,QAWGAN01,QAWGAN02',
    Notes:
      'PI PNR Update: If any update needs to be occurred for PNR.\r\nAutocancel is part of Upsell service.\r\nIRIS = Integrated Revenue Integrity Suit, an application part of revenue generated application. Does a validation of PNR (looks for faulty or suspicious PNR, then cancels it or updates it)\r\n',
    'Application Image':
      'https://lucid.app/documents/embedded/9a41d6af-c3dd-4806-9f7b-1f9dac9c5c83',
    'Who are my dependencies?': 'Shares, F5, MQ\r\n',
  },
  {
    'App Ref': '28',
    'App Key': 'EGO',
    'Application Name': 'PI ROBOTS',
    'PII Data': 'TRUE',
    'Tier Level': '3 - Less Critical',
    PCI: 'FALSE',
    'EQA Test Cases': 'TRUE',
    SME: 'Sim, Roger;Wareham, Shane;Baskaranth, Mahesh',
    'Queue Manager(s)': '[]',
    Nodes: '[]',
    'Application Image':
      'https://lucid.app/documents/embedded/cede49ab-f91b-4f50-8a82-76549da39883',
    'Who are my dependencies?':
      'PSS Turnpike (Nativehost)\r\nUDH Database (redshift)',
  },
  {
    'App Ref': '29',
    'App Key': 'EFE',
    'Application Name': 'PI SCEPTRE Data',
    'PII Data': 'TRUE',
    'Tier Level': '3 - Less Critical',
    PCI: 'FALSE',
    'EQA Test Cases': 'TRUE',
    SME: 'Anaganti, Naveen Kumar',
    'Queue Manager(s)': 'PIACMQ01,PIACMQ02,QIACMQ01,QIACMQ02,TIACMQ01,TIACMQ02',
    Nodes:
      'PAPBAN01,PAPBAN02,PAPBAN03,PAPBAN04,QAPBAN01,QAPBAN02,SAPBAN01,SAPBAN02',
    'Application Image':
      'https://lucid.app/documents/embedded/cede49ab-f91b-4f50-8a82-76549da39883',
    'Who are my dependencies?': 'NONE',
  },
  {
    'App Ref': '30',
    'App Key': 'AAB',
    'Application Name': 'PI Seat Reaccom',
    'PII Data': 'TRUE',
    'Tier Level': '3 - Less Critical',
    PCI: 'FALSE',
    'EQA Test Cases': 'TRUE',
    SME: 'Balasubramanian, Gayathri',
    'App Number': 12,
    'Queue Manager(s)': 'PIACMQ01,PIACMQ02,QIACMQ01,QIACMQ02,TIACMQ01,TIACMQ02',
    Nodes:
      'DAHAAN01,DCPMAN01,QAABAN01,QAABAN02,PAABAN01,PAABAN02,SAABAN01,SAABAN02',
    Notes:
      'PI Seat Reaccom: Used to reassign seats for requests from Shares, next it goes to PI, next PI reaches out to Seat Reacom Eng, next goes to Seat Assign, comes back to PI, finally we send to Shares\r\n\r\nSeat Reaccom Engine provides new seats where passengers get reacommodated\r\n\r\nTwo scenarios (types of request)\r\n1) Flights Swap\r\n2) Schedule Change\r\n',
    'Who are my dependencies?': 'Seat Reaccom Engine, MQ\r\n',
  },
  {
    'App Ref': '31',
    'App Key': 'CPH',
    'Application Name': 'PI Secure Channel',
    'PII Data': 'TRUE',
    'Tier Level': '1 - Critical',
    PCI: 'TRUE',
    'EQA Test Cases': 'FALSE',
    SME: 'Wareham, Shane',
    'App Number': 24,
    'Queue Manager(s)': '[]',
    Nodes: '[]',
    Notes: 'Not live yet - estimate Q3 2021',
    'Who are my dependencies?': 'MQ, Secure Channel to SHARES',
  },
  {
    'App Ref': '32',
    'App Key': 'BWX',
    'Application Name': 'PI SSM Conveyance',
    'PII Data': 'FALSE',
    'Tier Level': '1 - Critical',
    PCI: 'FALSE',
    'EQA Test Cases': 'TRUE',
    SME: 'Shubhajeet, Chakrabarty',
    'App Number': 19,
    'Queue Manager(s)': 'PIACMQ01,PIACMQ02,QIACMQ01,QIACMQ02,TIACMQ01,TIACMQ02',
    Nodes:
      'PBHFAN02,PBHFAN01,SBHFAN02,QBHFAN01,QBHFAN02, SBHFAN01,TAHAAN01,TAHAAN02',
    'Who are my dependencies?':
      ' VM , AWS-SQS , Python Script , MQ , Schedule Engine( Cloud )',
  },
  {
    'App Ref': '33',
    'App Key': 'BXU',
    'Application Name': 'PI Teletype Rejects',
    'PII Data': 'TRUE',
    'Tier Level': '3 - Less Critical',
    PCI: 'FALSE',
    'EQA Test Cases': 'FALSE',
    SME: 'Shubhajeet, Chakrabarty',
    'App Number': 14,
    'Queue Manager(s)':
      'PIACMQ01,PIACMQ02,QIACMQ01,QIACMQ02,TIACMQ01,TIACMQ02,DAAIMQ01',
    Nodes: 'TBXUAN01,TBXUAN02,PBXUAN01,PBXUAN02,QBXUAN02,QBXUAN01',
    Notes: 'Not live yet',
    'Who are my dependencies?':
      'OHS Rules, F5 , MQ , VM , ODM , SQL Database , AWS Kafka , Terminal Emulation , TPFComm( Token ).',
  },
  {
    'App Ref': '34',
    'App Key': 'ASH',
    'Application Name': 'PI Terminal Emulation',
    'PII Data': 'TRUE',
    'Tier Level': '4 - Not Critical',
    PCI: 'TRUE',
    'EQA Test Cases': 'TRUE',
    SME: 'Anaganti, Naveen',
    'App Number': 13,
    'Queue Manager(s)': 'PAWGMQ01,PAWGMQ02,SAWGMQ01,SAWGMQ02,DAWGMQ01,DAWGMQ02',
    Nodes: 'PAWGAN01,PAWGAN02,SAWGAN01,SAWGAN02,DAWGAN01,QAWGAN01,QAWGAN02',
    Notes:
      'PNR Services called by IRIS\r\nEMD - Electronic Miscellaneous Document',
    'Who are my dependencies?': 'Shares\r\n',
  },
  {
    'App Ref': '35',
    'App Key': 'CCI',
    'Application Name': 'PI Unified Flight Doc',
    'PII Data': 'TRUE',
    'Tier Level': '3 - Less Critical',
    PCI: 'FALSE',
    'EQA Test Cases': 'TRUE',
    SME: 'Fink, Mike',
    'App Number': 23,
    'Queue Manager(s)': '[]',
    Nodes: '[]',
    'Who are my dependencies?': 'NONE',
  },
  {
    'App Ref': '36',
    'App Key': 'AAI',
    'Application Name': 'PI Upsell Ancillaries',
    'PII Data': 'TRUE',
    'Tier Level': '2 - Somewhat Critical',
    PCI: 'TRUE',
    'EQA Test Cases': 'TRUE',
    SME: 'Anaganti, Naveen',
    'App Number': 15,
    'Queue Manager(s)': 'PIACMQ01,PIACMQ02,QIACMQ01,QIACMQ02,TIACMQ01,TIACMQ02',
    Nodes:
      'PAAIAN01,PAAIAN02,SAAIAN01,SAAIAN02,TAAIAN01,QAAIAN02,QAAIAN01,TAAIAN02',
    Notes: 'ODM = Operational Decision Manager',
    'Who are my dependencies?':
      'DataPower, Seats (Assign, Map), DataVault, Merchandising, PNR Retrieval, Eligible Form of Payment, Scheduled Engine, Database, Refund Cancel Seat Service, Reference Data, DataPowerToken, ODM\r\n',
  },
  {
    'App Ref': '37',
    'App Key': 'CPF',
    'Application Name': 'PI Utilities',
    'PII Data': 'TRUE',
    'Tier Level': '1 - Critical',
    PCI: 'FALSE',
    'EQA Test Cases': 'FALSE',
    SME: 'Wareham, Shane',
    'App Number': 25,
    'Queue Manager(s)': '[]',
    Nodes: '[]',
    'Who are my dependencies?': 'MQ',
  },
  {
    'App Ref': '38',
    'App Key': 'ADL',
    'Application Name': 'PSS Turnpike',
    'PII Data': 'TRUE',
    'Tier Level': '1 - Critical',
    PCI: 'TRUE',
    'EQA Test Cases': 'TRUE',
    SME: 'Wareham, Shane;Sim, Roger',
    'App Number': 26,
    'Queue Manager(s)': '[]',
    Nodes: '[]',
    'Who are my dependencies?':
      'VM, SHARES, DataPower, F5, FluentD, EBS Framework',
  },
  {
    'App Ref': '39',
    'App Key': 'ADL',
    'Application Name': 'TPK Scripter',
    'PII Data': 'TRUE',
    'Tier Level': '2 - Somewhat Critical',
    PCI: 'FALSE',
    'EQA Test Cases': 'TRUE',
    SME: 'Wareham, Shane',
    'Queue Manager(s)': '[]',
    Nodes: '[]',
    'Who are my dependencies?':
      'VM, SHARES, DataPower, F5, FluentD, EBS Framework',
  },
]
